### ISSUE TITLE
Redo date and time pickers.

### ISSUE THREAD

**Issue by ECourant** [ECourant/standards#19]
Because they are awful

**Comment by elliotcourant** [comment]
I've added the picker libraries needed. Make sure they play well with framework 7.

**Comment by elliotcourant** [comment]
- [x] redo create shift date and time pickers
- [ ] maybe redo pickers on the filter pages

**Comment by ECourant** [comment]
I'm not gonna redo the pickers on the filter pages because the calanders actually work pretty well.
